version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: drive_backend
    ports:
      - ${BACKEND_PORT}:8000
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: drive_frontend
    ports:
      - ${FRONTEND_PORT}:80
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always
